### ISSUE TITLE
Errno::EBADF: Bad file descriptor - not a socket file descriptor in Puma.

### ISSUE THREAD

**Issue by idyll** [puma/puma-dev#12]
I am not sure if this issue related to macOS 10.12.

I know there's an issue for go versions before 1.6.3 that causes all sorts of strange problems -- But I did try to locally on 1.6.3 compile and I see the same messages.

Here's what I see

```
test-app[6391]: Puma starting in single mode...
test-app[6391]: * Version 3.6.0 (ruby 2.2.5-p319), codename: Sleepy Sunday Serenity
test-app[6391]: * Min threads: 0, max threads: 5
test-app[6391]: * Environment: development
/Users/madsen/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/dragonfly-0.9.14/lib/dragonfly/data_storage/s3data_store.rb:27: warning: duplicated key at line 28 ignored: "sa-east-1"
test-app[6391]: * Inherited tcp://127.0.0.1:50144
test-app[6391]: bundler: failed to load command: puma (/Users/madsen/.rbenv/versions/2.2.5/bin/puma)
Errno::EBADF: Bad file descriptor - not a socket file descriptor
  /Users/madsen/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/puma-3.6.0/lib/puma/binder.rb:284:in `for_fd'
  /Users/madsen/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/puma-3.6.0/lib/puma/binder.rb:284:in `inherit_tcp_listener'
  /Users/madsen/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/puma-3.6.0/lib/puma/binder.rb:91:in `block in parse'
  /Users/madsen/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/puma-3.6.0/lib/puma/binder.rb:85:in `each'
  /Users/madsen/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/puma-3.6.0/lib/puma/binder.rb:85:in `parse'
  /Users/madsen/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/puma-3.6.0/lib/puma/runner.rb:133:in `load_and_bind'
  /Users/madsen/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/puma-3.6.0/lib/puma/single.rb:85:in `run'
  /Users/madsen/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/puma-3.6.0/lib/puma/launcher.rb:172:in `run'
  /Users/madsen/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/puma-3.6.0/lib/puma/cli.rb:74:in `run'
  /Users/madsen/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/puma-3.6.0/bin/puma:10:in `<top (required)>'
  /Users/madsen/.rbenv/versions/2.2.5/bin/puma:23:in `load'
  /Users/madsen/.rbenv/versions/2.2.5/bin/puma:23:in `<top (required)>'
* App 'test-app' shutdown and cleaned up
```

**Comment by billhorsman** [comment]
I get the same thing with Puma 3.4.0 and Ruby 2.3.1-p112. 

```
$ ./bin/puma-dev
[snip]
foo[70138]: * Version 3.4.0 (ruby 2.3.1-p112), codename: Owl Bowl Brawl
[snip]
bundler: failed to load command: puma (/Users/bill/.rbenv/versions/2.3.1/bin/puma)
```

Running the puma command manually does work (it complains about no configured application, as expected). 

```
$ /Users/bill/.rbenv/versions/2.3.1/bin/puma
Puma starting in single mode...
* Version 3.4.0 (ruby 2.3.1-p112), codename: Owl Bowl Brawl
* Min threads: 0, max threads: 16
* Environment: development
ERROR: No application configured, nothing to run
```

**Comment by idyll** [comment]
The no app configured message is because when you run it manually it is likely looking in a different directory for the app files.

**Comment by evanphx** [comment]
@billhorsman can you gist the entire output without snips? That context doesn't tell much of a picture.

**Comment by BJClark** [comment]
Here is the full context for me when I get this error: https://gist.github.com/BJClark/4884bc5497c94d18dec230d9af87cc88
