### ISSUE TITLE
Getting "Bad file descriptor - not a socket file descriptor" with 0.4.

### ISSUE THREAD

**Issue by paulca** [puma/puma-dev#16]
I'll keep trying to work through this, but here's the latest backtrace from `puma-dev.log`

(seemed to figure out my launchd issues anyway!)

```
passbook-tito[13567]: Puma starting in single mode...
passbook-tito[13567]: * Version 3.6.0 (ruby 2.3.0-p0), codename: Sleepy Sunday Serenity
passbook-tito[13567]: * Min threads: 0, max threads: 5
passbook-tito[13567]: * Environment: development
passbook-tito[13567]: * Inherited tcp://127.0.0.1:54367
Errno::EBADF: Bad file descriptor - not a socket file descriptor
  /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/binder.rb:284:in `for_fd'
  /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/binder.rb:284:in `inherit_tcp_listener'
  /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/binder.rb:91:in `block in parse'
  /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/binder.rb:85:in `each'
  /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/binder.rb:85:in `parse'
  /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/runner.rb:133:in `load_and_bind'
  /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/single.rb:85:in `run'
  /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/launcher.rb:172:in `run'
  /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/cli.rb:74:in `run'
  /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/puma-3.6.0/bin/puma:10:in `<top (required)>'
  /usr/local/var/rbenv/versions/2.3.0/bin/puma:23:in `load'
  /usr/local/var/rbenv/versions/2.3.0/bin/puma:23:in `<top (required)>'
passbook-tito[13567]: bundler: failed to load command: puma (/usr/local/var/rbenv/versions/2.3.0/bin/puma)
* App 'passbook-tito' shutdown and cleaned up
```

**Comment by paulca** [comment]
Sorry, this is a dupe of #12
