### ISSUE TITLE
Incompatible library version error when app's RVM ruby version is lower than a homebrew-installed ruby

### ISSUE THREAD

**Issue by rrosen** [puma/puma-dev#173]
Having issues loading up a project in puma-dev.  The project runs ruby 2.2 via RVM and I get this from the console output:

```
fca-website[6461]: /usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:59:in `require': incompatible library version - /Users/rrosen/.rvm/gems/ruby-2.2.2/gems/puma-3.12.0/lib/puma/puma_http11.bundle (LoadError)
fca-website[6461]:  from /usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:59:in `require'
fca-website[6461]:  from /Users/rrosen/.rvm/gems/ruby-2.2.2/gems/puma-3.12.0/lib/puma/server.rb:15:in `<top (required)>'
fca-website[6461]:  from /usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:59:in `require'
fca-website[6461]:  from /usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:59:in `require'
fca-website[6461]:  from /Users/rrosen/.rvm/gems/ruby-2.2.2/gems/puma-3.12.0/lib/puma/runner.rb:1:in `<top (required)>'
fca-website[6461]:  from /usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:59:in `require'
fca-website[6461]:  from /usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:59:in `require'
fca-website[6461]:  from /Users/rrosen/.rvm/gems/ruby-2.2.2/gems/puma-3.12.0/lib/puma/cluster.rb:1:in `<top (required)>'
fca-website[6461]:  from /usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:59:in `require'
fca-website[6461]:  from /usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:59:in `require'
fca-website[6461]:  from /Users/rrosen/.rvm/gems/ruby-2.2.2/gems/puma-3.12.0/lib/puma/launcher.rb:4:in `<top (required)>'
fca-website[6461]:  from /usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:59:in `require'
fca-website[6461]:  from /usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:59:in `require'
fca-website[6461]:  from /Users/rrosen/.rvm/gems/ruby-2.2.2/gems/puma-3.12.0/lib/puma/cli.rb:6:in `<top (required)>'
fca-website[6461]:  from /usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:59:in `require'
fca-website[6461]:  from /usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:59:in `require'
fca-website[6461]:  from /Users/rrosen/.rvm/gems/ruby-2.2.2/gems/puma-3.12.0/bin/puma:6:in `<top (required)>'
fca-website[6461]:  from /Users/rrosen/.rvm/gems/ruby-2.2.2/bin/puma:23:in `load'
fca-website[6461]:  from /Users/rrosen/.rvm/gems/ruby-2.2.2/bin/puma:23:in `<main>'
fca-website[6461]:  from /Users/rrosen/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:24:in `eval'
fca-website[6461]:  from /Users/rrosen/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:24:in `<main>'
! Killing 'fca-website' (6461)
* App 'fca-website' shutdown and cleaned up
! Detecting app 'fca-website' dying on start
```

I have ruby 2.3.1 installed in homebrew as a dependency for vim.  Looks like it's trying to load up the 2.2 puma gem within ruby 2.3.

Uninstalling the homebrew ruby gets the app to load in puma-dev (but breaks the homebrew packages that depend on it 😞)

Interestingly enough, I don't get this issue with other RVM projects that use ruby 2.4 or 2.5

**Comment by arielscherman** [comment]
Have you found a fix for this issue? I'm having a similar error but with passenger instead of puma.
