### ISSUE TITLE
App doesn't load

### ISSUE THREAD

**Issue by ManuelFrigerio** [puma/puma-dev#180]
Hi,

I've spent the last 4 hours trying to fix this but without success.
I've followed all the instructions to install puma-dev on the .test domain.
I then run `puma-dev` and I get this as expected

```
* Directory for apps: /Users/manuelfrigerio/.puma-dev
* Domains: test
* DNS Server port: 9253
* HTTP Server port: 9280
* HTTPS Server port: 9283
! Puma dev listening on http and https
```

However, when I visit the page mywebsite.test:9280, it keeps loading but never shows the page.
I only get this error on the screen:

> This page isn’t working
> onward-web.test is currently unable to handle this request.
> HTTP ERROR 500

This is the full log trace:

```
* Directory for apps: /Users/manuelfrigerio/.puma-dev
* Domains: test
* DNS Server port: 9253
* HTTP Server port: 9280
* HTTPS Server port: 9283
! Puma dev listening on http and https
! Booting app 'onward-web' on socket /Users/manuelfrigerio/.puma-dev/onward-web/tmp/puma-dev-48760.sock
onward-web[48764]: bash: no job control in this shell
onward-web[48764]: SSH_AUTH_SOCK=/var/folders/p0/pv4_sbqs21zc_0nc0k1y_jn40000gn/T//ssh-8N2E6W1V1Ntt/agent.48849; export SSH_AUTH_SOCK;
onward-web[48764]: SSH_AGENT_PID=48850; export SSH_AGENT_PID;
onward-web[48764]: echo Agent pid 48850;
onward-web[48764]: Identity added: /Users/manuelfrigerio/.ssh/id_rsa (/Users/manuelfrigerio/.ssh/id_rsa)
onward-web[48764]: Ignoring bcrypt-3.1.12 because its extensions are not built.  Try: gem pristine bcrypt --version 3.1.12
onward-web[48764]: Ignoring byebug-10.0.2 because its extensions are not built.  Try: gem pristine byebug --version 10.0.2
onward-web[48764]: Ignoring executable-hooks-1.5.0 because its extensions are not built.  Try: gem pristine executable-hooks --version 1.5.0
onward-web[48764]: Ignoring fast_blank-0.0.2 because its extensions are not built.  Try: gem pristine fast_blank --version 0.0.2
onward-web[48764]: Ignoring fast_xor-1.1.3 because its extensions are not built.  Try: gem pristine fast_xor --version 1.1.3
onward-web[48764]: Ignoring fast_xs-0.8.0 because its extensions are not built.  Try: gem pristine fast_xs --version 0.8.0
onward-web[48764]: Ignoring ffi-1.9.18 because its extensions are not built.  Try: gem pristine ffi --version 1.9.18
onward-web[48764]: Ignoring gem-wrappers-1.3.2 because its extensions are not built.  Try: gem pristine gem-wrappers --version 1.3.2
onward-web[48764]: Ignoring hiredis-0.5.2 because its extensions are not built.  Try: gem pristine hiredis --version 0.5.2
onward-web[48764]: Ignoring http_parser.rb-0.6.0 because its extensions are not built.  Try: gem pristine http_parser.rb --version 0.6.0
onward-web[48764]: Ignoring json-1.8.6 because its extensions are not built.  Try: gem pristine json --version 1.8.6
onward-web[48764]: Ignoring kgio-2.9.3 because its extensions are not built.  Try: gem pristine kgio --version 2.9.3
onward-web[48764]: Ignoring lz4-ruby-0.3.3 because its extensions are not built.  Try: gem pristine lz4-ruby --version 0.3.3
onward-web[48764]: Ignoring nio4r-2.1.0 because its extensions are not built.  Try: gem pristine nio4r --version 2.1.0
onward-web[48764]: Ignoring nokogiri-1.8.1 because its extensions are not built.  Try: gem pristine nokogiri --version 1.8.1
onward-web[48764]: Ignoring pg-0.21.0 because its extensions are not built.  Try: gem pristine pg --version 0.21.0
onward-web[48764]: Ignoring psych-2.2.4 because its extensions are not built.  Try: gem pristine psych --version 2.2.4
onward-web[48764]: Ignoring puma-3.10.0 because its extensions are not built.  Try: gem pristine puma --version 3.10.0
onward-web[48764]: Ignoring redcarpet-3.4.0 because its extensions are not built.  Try: gem pristine redcarpet --version 3.4.0
onward-web[48764]: Ignoring rgeo-1.1.1 because its extensions are not built.  Try: gem pristine rgeo --version 1.1.1
onward-web[48764]: Ignoring skylight-2.0.2 because its extensions are not built.  Try: gem pristine skylight --version 2.0.2
onward-web[48764]: Ignoring unf_ext-0.0.7.4 because its extensions are not built.  Try: gem pristine unf_ext --version 0.0.7.4
onward-web[48764]: Ignoring websocket-driver-0.6.5 because its extensions are not built.  Try: gem pristine websocket-driver --version 0.6.5
onward-web[48764]: Ignoring yajl-ruby-1.2.2 because its extensions are not built.  Try: gem pristine yajl-ruby --version 1.2.2
onward-web[48764]: /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': incompatible library version - /Users/manuelfrigerio/.rvm/gems/ruby-2.4.3/gems/puma-3.10.0/lib/puma/puma_http11.bundle (LoadError)
onward-web[48764]: 	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
onward-web[48764]: 	from /Users/manuelfrigerio/.rvm/gems/ruby-2.4.3/gems/puma-3.10.0/lib/puma/server.rb:15:in `<top (required)>'
onward-web[48764]: 	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
onward-web[48764]: 	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
onward-web[48764]: 	from /Users/manuelfrigerio/.rvm/gems/ruby-2.4.3/gems/puma-3.10.0/lib/puma/runner.rb:1:in `<top (required)>'
onward-web[48764]: 	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
onward-web[48764]: 	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
onward-web[48764]: 	from /Users/manuelfrigerio/.rvm/gems/ruby-2.4.3/gems/puma-3.10.0/lib/puma/cluster.rb:1:in `<top (required)>'
onward-web[48764]: 	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
onward-web[48764]: 	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
onward-web[48764]: 	from /Users/manuelfrigerio/.rvm/gems/ruby-2.4.3/gems/puma-3.10.0/lib/puma/launcher.rb:4:in `<top (required)>'
onward-web[48764]: 	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
onward-web[48764]: 	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
onward-web[48764]: 	from /Users/manuelfrigerio/.rvm/gems/ruby-2.4.3/gems/puma-3.10.0/lib/puma/cli.rb:5:in `<top (required)>'
onward-web[48764]: 	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
onward-web[48764]: 	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
onward-web[48764]: 	from /Users/manuelfrigerio/.rvm/gems/ruby-2.4.3/gems/puma-3.10.0/bin/puma:6:in `<top (required)>'
onward-web[48764]: 	from /Users/manuelfrigerio/.rvm/gems/ruby-2.4.3/bin/puma:26:in `load'
onward-web[48764]: 	from /Users/manuelfrigerio/.rvm/gems/ruby-2.4.3/bin/puma:26:in `<main>'
onward-web[48764]: 	from /Users/manuelfrigerio/.rvm/gems/ruby-2.4.3/bin/ruby_executable_hooks:24:in `eval'
onward-web[48764]: 	from /Users/manuelfrigerio/.rvm/gems/ruby-2.4.3/bin/ruby_executable_hooks:24:in `<main>'
```

Any help would be appreciated :)

**Comment by ManuelFrigerio** [comment]
No help whatsoever? :(

**Comment by nonrational** [comment]
I suspect your rvm may be misconfigured. I'd start there. Do you have a `.ruby-version` in your project? 

From the backtrace you posted, it looks as though macOS system ruby-2.3.0 and .rvm ruby-2.4.3 are stepping on each-other:
```
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': incompatible library version - /Users/manuelfrigerio/.rvm/gems/ruby-2.4.3/gems/puma-3.10.0/lib/puma/puma_http11.bundle (LoadError)
```

**Comment by ManuelFrigerio** [comment]
Hi @nonrational thanks for the help!
Yes, I do have a `.ruby-version` file which says `2.4.3`

"From the backtrace you posted, it looks as though macOS system ruby-2.3.0 and .rvm ruby-2.4.3 are stepping on each-other:"
How would I fix this?

**Comment by kurko** [comment]
Same here. `puma-dev -stop` didn't work. Had to `kill -9 $PUMA_PID`, which then worked.

**Comment by stereodenis** [comment]
`puma-dev link`, then simply open mywebsite.test without port number

**Comment by wade-welles** [comment]
what do you mean by open? 

I run the puma-dev then get `application uknown`. I have the application symlinked to the ~/.puma folder, and everything runs fine. I have it working with other rack applications. Does puma vanilla need to be running and connecting to the puma-dev socket?

**Comment by nonrational** [comment]
I think this is related to upgrading your macOS version after installing gems via ruby-build and rvm/rbenv. All of the native extensions need to be rebuilt. 

Probably easiest to `rm -rf $HOME/.rvm/gems/` and `bundle` again.

Given this issue has fragmented into few topics, going to close for now. Happy to re-open if people are still having this issue.
