### ISSUE TITLE
Unable to boot with ruby-2.5.3 "Unexpected Exit"

### ISSUE THREAD

**Issue by tomrossi7** [puma/puma-dev#185]
I'm unable to access my site with puma-dev since upgrading Ruby and Rails. From looking at the output below, it appears to get thrown off by the multiple ruby versions. I have a `.ruby-version` and a `.ruby-gemset` so **I'm not sure why it is looking in the old ruby 2.3.3 folder for the Puma gem?** 

Incidentally, I don't have any of the following files: `~/.powconfig` .`env` .`powrc` `.powenv`.

```
$ puma-dev
* Directory for apps: /Users/tom/.puma-dev
* Domains: test
* DNS Server port: 9253
* HTTP Server port: 9280
* HTTPS Server port: 9283
! Puma dev listening on http and https
! Booting app 'donortools2' on socket /Users/tom/.puma-dev/donortools2/tmp/puma-dev-5052.sock
donortools2[5056]: bash: no job control in this shell
donortools2[5056]: /Users/tom/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems.rb:289:in `find_spec_for_exe': can't find gem puma (>= 0.a) with executable puma (Gem::GemNotFoundException)
donortools2[5056]: 	from /Users/tom/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems.rb:308:in `activate_bin_path'
donortools2[5056]: 	from /Users/tom/.rvm/gems/ruby-2.5.3@donortools2/bin/puma:23:in `<main>'
donortools2[5056]: 	from /Users/tom/.rvm/gems/ruby-2.3.3@global/bin/ruby_executable_hooks:24:in `eval'
donortools2[5056]: 	from /Users/tom/.rvm/gems/ruby-2.3.3@global/bin/ruby_executable_hooks:24:in `<main>'
! Killing 'donortools2' (5056)
* App 'donortools2' shutdown and cleaned up
! Detecting app 'donortools2' dying on start

$ curl donortools2.test
unexpected exit:
	bash: line 23: exec: puma: not found

$ cat .ruby-version
ruby-2.5.3

$ cat .ruby-gemset
donortools2

$ which puma
../.rvm/gems/ruby-2.5.3@donortools2/bin/puma

**Comment by tomrossi7** [comment]
It's almost like it doesn't recognize that puma has been installed in the apps bundle?

Possibly an RVM configuration issue?

**Comment by tomrossi7** [comment]
I can't explain it, but this solved the problem for me. I grabbed an old `.powenv` file from a pow application and that got it working. I'll include it here for anyone who gets stuck here:

**.powenv**
```
# detect `$rvm_path`
if [ -z "${rvm_path:-}" ] && [ -x "${HOME:-}/.rvm/bin/rvm" ]
then rvm_path="${HOME:-}/.rvm"
fi
if [ -z "${rvm_path:-}" ] && [ -x "/usr/local/rvm/bin/rvm" ]
then rvm_path="/usr/local/rvm"
fi

# load environment of current project ruby
if
  [ -n "${rvm_path:-}" ] &&
  [ -x "${rvm_path:-}/bin/rvm" ] &&
  rvm_project_environment=`"${rvm_path:-}/bin/rvm" . do rvm env --path 2>/dev/null` &&
  [ -n "${rvm_project_environment:-}" ] &&
  [ -s "${rvm_project_environment:-}" ]
then
  echo "RVM loading: ${rvm_project_environment:-}"
  \. "${rvm_project_environment:-}"
else
  echo "RVM project not found at: $PWD"
fi
```

**Comment by hopewise** [comment]
I tried to put that `.powenv` at the root of project, but I still get the same error
