### ISSUE TITLE
dying on start..

### ISSUE THREAD

**Issue by hopewise** [puma/puma-dev#294]
My would dyes when I do the request at browser, 
```
puma-dev -V
Version: 0.17.0 (go1.17.2)
```

I am getting this:

```
backend-4cc1c336[59755]: Puma starting in single mode...
backend-4cc1c336[59755]: * Puma version: 5.5.2 (ruby 2.5.0-p0) ("Zawgyi")
backend-4cc1c336[59755]: *  Min threads: 0
backend-4cc1c336[59755]: *  Max threads: 5
backend-4cc1c336[59755]: *  Environment: development
backend-4cc1c336[59755]: *          PID: 59755
backend-4cc1c336[59755]: WARNING: Nokogiri was built against LibXML version 2.9.12, but has dynamically loaded 2.9.4
backend-4cc1c336[59755]: /Users/samir/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/redis-3.2.2/lib/redis/client.rb:441: warning: constant ::Fixnum is deprecated
backend-4cc1c336[59755]: /Users/samir/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/redis-3.2.2/lib/redis/client.rb:441: warning: constant ::Fixnum is deprecated
backend-4cc1c336[59755]: * Listening on unix:/Users/samir/.puma-dev/admin.myapp/tmp/puma-dev-13166.sock
backend-4cc1c336[59755]: /Users/samir/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require': cannot load such file -- nio (LoadError)
backend-4cc1c336[59755]: 	from /Users/samir/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
backend-4cc1c336[59755]: 	from /Users/samir/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
backend-4cc1c336[59755]: 	from /Users/samir/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
backend-4cc1c336[59755]: 	from /Users/samir/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/puma-5.5.2/lib/puma/reactor.rb:24:in `initialize'
backend-4cc1c336[59755]: 	from /Users/samir/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/puma-5.5.2/lib/puma/server.rb:242:in `new'
backend-4cc1c336[59755]: 	from /Users/samir/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/puma-5.5.2/lib/puma/server.rb:242:in `run'
backend-4cc1c336[59755]: 	from /Users/samir/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/puma-5.5.2/lib/puma/single.rb:53:in `run'
backend-4cc1c336[59755]: 	from /Users/samir/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/puma-5.5.2/lib/puma/launcher.rb:181:in `run'
backend-4cc1c336[59755]: 	from /Users/samir/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/puma-5.5.2/lib/puma/cli.rb:80:in `run'
backend-4cc1c336[59755]: 	from /Users/samir/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/puma-5.5.2/bin/puma:10:in `<top (required)>'
backend-4cc1c336[59755]: 	from /Users/samir/.asdf/installs/ruby/2.5.0/bin/puma:23:in `load'
backend-4cc1c336[59755]: 	from /Users/samir/.asdf/installs/ruby/2.5.0/bin/puma:23:in `<main>'
! Killing 'backend-4cc1c336' (59755) - 'stdout/stderr closed'
* App 'backend-4cc1c336' shutdown and cleaned up
! Detecting app 'backend-4cc1c336' dying on start
```

Any idea?

**Comment by nonrational** [comment]
`Nokogiri was built against LibXML version 2.9.12, but has dynamically loaded 2.9.4` seems to suggest that there's an issue with your ruby environment or with puma-dev loading your ruby environment. 

Might be related to https://github.com/puma/puma-dev/issues/187 ?
