### ISSUE TITLE
Is puma required in Gemfile?

### ISSUE THREAD

**Issue by JustinAiken** [puma/puma-dev#31]
I installed the `puma` gem in the global gemset for the ruby, but puma-dev doesn't hook into it unless it's added to the app's `Gemfile`:

```bash
$ which puma
/Users/jaiken/.rvm/gems/ruby-2.3.1/bin/puma

$ puma-dev
* Directory for apps: /Users/jaiken/.puma-dev
* Domains: dev
* DNS Server port: 9253
* HTTP Server port: 9280
* HTTPS Server port: 9283
! Puma dev listening on http and https
! Booted app 'usertesting' on socket /Users/jaiken/.puma-dev/usertesting/tmp/puma-dev-12773.sock
usertesting[12823]: Using /Users/jaiken/.rvm/gems/ruby-2.3.1
usertesting[12823]: Using /Users/jaiken/.rvm/gems/ruby-2.3.1
/Users/jaiken/.rvm/gems/ruby-2.3.1/gems/bundler-1.12.5/lib/bundler/rubygems_integration.rb:373:in `block in replace_bin_path': can't find executable puma (Gem::Exception)
	from /Users/jaiken/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems.rb:298:in `activate_bin_path'
	from /Users/jaiken/.rvm/gems/ruby-2.3.1/bin/puma:22:in `<main>'
	from /Users/jaiken/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/jaiken/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
```

Is putting `puma` in the `Gemfile` required, or is this a bug?

**Comment by evanphx** [comment]
Yes, puma is required in the Gemfile.

**Comment by evanphx** [comment]
I suppose I could add code to check that puma is in the Gemfile, but the result will be the same regardless, the user adding it to the Gemfile.
