### ISSUE TITLE
puma-dev stopped working

### ISSUE THREAD

**Issue by arrowcircle** [puma/puma-dev#63]
Hi! I tried to move from pow to puma-dev today.
First two symlinked apps worked great, but after linking two more apps it stopped working at all.

I tried to `pkill -5 puma-dev`, but now now event first two apps dont work.

Here is the output from logs of pkill -5

```
SIGTRAP: trace trap
PC=0x406159b m=0

goroutine 0 [idle]:
runtime.mach_semaphore_wait(0x7fff0000030b, 0x0, 0x4b69760, 0x40548a0, 0xc81fff7dff, 0x4729f60, 0x4054d89, 0xffffffffffffffff, 0x4019712, 0x7fff5fbffb2c, ...)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/sys_darwin_amd64.s:416 +0xb
runtime.semasleep1(0xffffffffffffffff, 0x4019712)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/os1_darwin.go:423 +0xdf
runtime.semasleep.func1()
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/os1_darwin.go:439 +0x29
runtime.systemstack(0x7fff5fbffb30)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/asm_amd64.s:307 +0xab
runtime.semasleep(0xffffffffffffffff, 0x0)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/os1_darwin.go:440 +0x36
runtime.notesleep(0x472a828)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/lock_sema.go:166 +0xed
runtime.stoplockedm()
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/proc.go:1685 +0xae
runtime.schedule()
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/proc.go:2033 +0x6e
runtime.park_m(0xc820074600)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/proc.go:2140 +0x18b
runtime.mcall(0x7fff5fbffc30)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/asm_amd64.s:233 +0x5b

goroutine 20 [select, locked to thread]:
runtime.gopark(0x45b2530, 0xc820025728, 0x44f5958, 0x6, 0x18, 0x2)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/proc.go:262 +0x163 fp=0xc820025510 sp=0xc8200254e8
runtime.selectgoImpl(0xc820025728, 0x0, 0x18)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/select.go:392 +0xa67 fp=0xc8200256d0 sp=0xc820025510
runtime.selectgo(0xc820025728)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/select.go:215 +0x12 fp=0xc8200256f0 sp=0xc8200256d0
runtime.ensureSigM.func1()
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/signal1_unix.go:279 +0x32c fp=0xc8200257c0 sp=0xc8200256f0
runtime.goexit()
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc8200257c8 sp=0xc8200257c0
created by runtime.ensureSigM
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/signal1_unix.go:292 +0xd0

goroutine 1 [chan receive]:
gopkg.in/tomb%2ev2.(*Tomb).Wait(0xc82012df20, 0x0, 0x0)
	/Users/evan/git/puma-dev/vendor/src/gopkg.in/tomb.v2/tomb.go:116 +0x58
puma/dev.(*HTTPServer).Serve(0xc820130e10, 0x44f3060, 0x6, 0x0, 0x0)
	/Users/evan/git/puma-dev/src/puma/dev/http_darwin.go:73 +0x2ee
main.main()
	/Users/evan/git/puma-dev/src/cmd/puma-dev/main_darwin.go:162 +0x1561

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/asm_amd64.s:1998 +0x1

goroutine 19 [syscall]:
os/signal.signal_recv(0x0)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/sigqueue.go:116 +0x132
os/signal.loop()
	/usr/local/Cellar/go/1.6.3/libexec/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/Cellar/go/1.6.3/libexec/src/os/signal/signal_unix.go:28 +0x37

goroutine 21 [chan receive]:
main.main.func1(0xc82007a4e0, 0xc82006c680)
	/Users/evan/git/puma-dev/src/cmd/puma-dev/main_darwin.go:95 +0x36
created by main.main
	/Users/evan/git/puma-dev/src/cmd/puma-dev/main_darwin.go:98 +0x88a

goroutine 22 [chan receive]:
main.main.func2(0xc82007a660, 0xc82006c680)
	/Users/evan/git/puma-dev/src/cmd/puma-dev/main_darwin.go:105 +0x36
created by main.main
	/Users/evan/git/puma-dev/src/cmd/puma-dev/main_darwin.go:109 +0xaa7

goroutine 23 [semacquire]:
sync.runtime_Semacquire(0xc820065f1c)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/sema.go:47 +0x26
sync.(*WaitGroup).Wait(0xc820065f10)
	/usr/local/Cellar/go/1.6.3/libexec/src/sync/waitgroup.go:127 +0xb4
puma/dev.(*DNSResponder).Serve(0xc820065df0, 0xc820065280, 0x1, 0x1, 0x0, 0x0)
	/Users/evan/git/puma-dev/src/puma/dev/dns.go:87 +0x25a
created by main.main
	/Users/evan/git/puma-dev/src/cmd/puma-dev/main_darwin.go:137 +0x11d3

goroutine 24 [chan receive]:
gopkg.in/tomb%2ev2.(*Tomb).Wait(0xc8201401b0, 0x0, 0x0)
	/Users/evan/git/puma-dev/vendor/src/gopkg.in/tomb.v2/tomb.go:116 +0x58
puma/dev.(*HTTPServer).ServeTLS(0xc820130e10, 0x44fba90, 0x9, 0x0, 0x0)
	/Users/evan/git/puma-dev/src/puma/dev/http_darwin.go:46 +0x5b9
created by main.main
	/Users/evan/git/puma-dev/src/cmd/puma-dev/main_darwin.go:160 +0x1536

goroutine 25 [IO wait]:
net.runtime_pollWait(0x5c09a88, 0x72, 0x5c00028)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc820125e20, 0x72, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.3/libexec/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820125e20, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.3/libexec/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc820125dc0, 0x0, 0x5c09b80, 0xc820133240)
	/usr/local/Cellar/go/1.6.3/libexec/src/net/fd_unix.go:426 +0x27c
net.(*TCPListener).AcceptTCP(0xc820070068, 0x1, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.3/libexec/src/net/tcpsock_posix.go:254 +0x4d
net.(*TCPListener).Accept(0xc820070068, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.3/libexec/src/net/tcpsock_posix.go:264 +0x3d
net/http.(*Server).Serve(0xc820122880, 0x5c09b48, 0xc820070068, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.3/libexec/src/net/http/server.go:2117 +0x129
puma/dev.(*HTTPServer).Serve.func1(0x0, 0x0)
	/Users/evan/git/puma-dev/src/puma/dev/http_darwin.go:69 +0x43
gopkg.in/tomb%2ev2.(*Tomb).run(0xc82012df20, 0xc8201331e0)
	/Users/evan/git/puma-dev/vendor/src/gopkg.in/tomb.v2/tomb.go:153 +0x21
created by gopkg.in/tomb%2ev2.(*Tomb).Go
	/Users/evan/git/puma-dev/vendor/src/gopkg.in/tomb.v2/tomb.go:149 +0x131

goroutine 26 [IO wait]:
net.runtime_pollWait(0x5c09848, 0x72, 0xc82014a91c)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc820152060, 0x72, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.3/libexec/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820152060, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.3/libexec/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).readMsg(0xc820152000, 0xc820170a00, 0x200, 0x200, 0xc820140600, 0x28, 0x28, 0xffffffffffffffff, 0x0, 0x0, ...)
	/usr/local/Cellar/go/1.6.3/libexec/src/net/fd_unix.go:304 +0x33d
net.(*UDPConn).ReadMsgUDP(0xc820154000, 0xc820170a00, 0x200, 0x200, 0xc820140600, 0x28, 0x28, 0x200, 0x43b8e40, 0x1, ...)
	/usr/local/Cellar/go/1.6.3/libexec/src/net/udpsock_posix.go:96 +0x171
github.com/miekg/dns.ReadFromSessionUDP(0xc820154000, 0xc820170a00, 0x200, 0x200, 0x200, 0x200, 0x0, 0x0)
	/Users/evan/git/puma-dev/vendor/src/github.com/miekg/dns/udp.go:47 +0xc1
github.com/miekg/dns.(*Server).readUDP(0xc820142000, 0xc820154000, 0x77359400, 0x0, 0x0, 0x0, 0xc8201420c0, 0x0, 0x0)
	/Users/evan/git/puma-dev/vendor/src/github.com/miekg/dns/server.go:647 +0x190
github.com/miekg/dns.(*defaultReader).ReadUDP(0xc820154008, 0xc820154000, 0x77359400, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/evan/git/puma-dev/vendor/src/github.com/miekg/dns/server.go:254 +0x5f
github.com/miekg/dns.(*Server).serveUDP(0xc820142000, 0xc820154000, 0x0, 0x0)
	/Users/evan/git/puma-dev/vendor/src/github.com/miekg/dns/server.go:520 +0x207
github.com/miekg/dns.(*Server).ListenAndServe(0xc820142000, 0x0, 0x0)
	/Users/evan/git/puma-dev/vendor/src/github.com/miekg/dns/server.go:371 +0x7ca
puma/dev.(*DNSResponder).Serve.func1(0xc820065f10, 0xc820065e10, 0xe)
	/Users/evan/git/puma-dev/src/puma/dev/dns.go:78 +0xad
created by puma/dev.(*DNSResponder).Serve
	/Users/evan/git/puma-dev/src/puma/dev/dns.go:79 +0x210

goroutine 27 [IO wait]:
net.runtime_pollWait(0x5c099c8, 0x72, 0x5c00028)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc820125e90, 0x72, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.3/libexec/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820125e90, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.3/libexec/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc820125e30, 0x0, 0x5c09b80, 0xc8201332c0)
	/usr/local/Cellar/go/1.6.3/libexec/src/net/fd_unix.go:426 +0x27c
net.(*TCPListener).AcceptTCP(0xc820070070, 0x40118cd, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.3/libexec/src/net/tcpsock_posix.go:254 +0x4d
net.(*TCPListener).Accept(0xc820070070, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.3/libexec/src/net/tcpsock_posix.go:264 +0x3d
github.com/miekg/dns.(*Server).serveTCP(0xc8200ea9c0, 0x5c09b48, 0xc820070070, 0x0, 0x0)
	/Users/evan/git/puma-dev/vendor/src/github.com/miekg/dns/server.go:477 +0x1dd
github.com/miekg/dns.(*Server).ListenAndServe(0xc8200ea9c0, 0x0, 0x0)
	/Users/evan/git/puma-dev/vendor/src/github.com/miekg/dns/server.go:335 +0x486
puma/dev.(*DNSResponder).Serve.func2(0xc820065f10, 0xc820065e10, 0xe)
	/Users/evan/git/puma-dev/src/puma/dev/dns.go:84 +0xad
created by puma/dev.(*DNSResponder).Serve
	/Users/evan/git/puma-dev/src/puma/dev/dns.go:85 +0x24c

goroutine 28 [IO wait]:
net.runtime_pollWait(0x5c09908, 0x72, 0x5c00028)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc820125f00, 0x72, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.3/libexec/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820125f00, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.3/libexec/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc820125ea0, 0x0, 0x5c09b80, 0xc820133420)
	/usr/local/Cellar/go/1.6.3/libexec/src/net/fd_unix.go:426 +0x27c
net.(*TCPListener).AcceptTCP(0xc820070098, 0x40ee998, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.3/libexec/src/net/tcpsock_posix.go:254 +0x4d
net.(*TCPListener).Accept(0xc820070098, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.3/libexec/src/net/tcpsock_posix.go:264 +0x3d
crypto/tls.(*listener).Accept(0xc8201333a0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.3/libexec/src/crypto/tls/tls.go:52 +0x60
net/http.(*Server).Serve(0xc820122900, 0x5c09c70, 0xc8201333a0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.3/libexec/src/net/http/server.go:2117 +0x129
puma/dev.(*HTTPServer).ServeTLS.func1(0x0, 0x0)
	/Users/evan/git/puma-dev/src/puma/dev/http_darwin.go:42 +0x43
gopkg.in/tomb%2ev2.(*Tomb).run(0xc8201401b0, 0xc8201333c0)
	/Users/evan/git/puma-dev/vendor/src/gopkg.in/tomb.v2/tomb.go:153 +0x21
created by gopkg.in/tomb%2ev2.(*Tomb).Go
	/Users/evan/git/puma-dev/vendor/src/gopkg.in/tomb.v2/tomb.go:149 +0x131

rax    0xe
rbx    0x472a720
rcx    0x7fff5fbffab8
rdx    0x7fff5fbffb30
rdi    0x30b
rsi    0xc8200257a0
rbp    0x30b
rsp    0x7fff5fbffab8
r8     0x472a720
r9     0x0
r10    0x0
r11    0x286
r12    0x8
r13    0x45b00f4
r14    0x9
r15    0x8
rip    0x406159b
rflags 0x286
cs     0x7
fs     0x0
gs     0x0
* Directory for apps: /Users/ionbuggy/.puma-dev
* Domains: dev
* DNS Server port: 9253
* HTTP Server port: inherited from launchd
* HTTPS Server port: inherited from launchd
! Puma dev listening on http and https
```

After restart no apps work and logs are empty. In browser, I got "domain.dev server DNS address could not be found"

How to solve this problem?

**Comment by evanphx** [comment]
Please try doing `puma-dev -unistall` then `puma-dev -install` and see if it works again.

**Comment by evanphx** [comment]
Could you try the latest release and tell me if you have the same issue?

**Comment by arrowcircle** [comment]
Hi! How to properly install latest release if I installed puma-dev via homebrew? It says no updates are available.

I tried to uninstall and install puma-dev, now I get only one message in logs.

```
2016/08/15 11:48:20 Unable to expand dir: exit status 1
```

I tried to unlink and link apps to ~/.puma-dev, but its sill the same log message

**Comment by attilagyorffy** [comment]
@arrowcircle you could try cloning the project from gh, setting up Go and doing a make as per the README. That's how I ended up following the bleeding edge (which is often a great way to send PRs and bug reports)

**Comment by attilagyorffy** [comment]
(Alternatively I could create a binary off the latest master and push it up for you if you are on OSX 10.11.6)

**Comment by evanphx** [comment]
@arrowcircle You need to run `brew update` to see the newest version. You should see at least v0.9 as of today.

**Comment by arrowcircle** [comment]
@evanphx, @attilagyorffy Thanks for the help. Now apps works fine both http and https.
But logs are still full of 

```
2016/08/15 20:20:32 Unable to expand dir: exit status 1
2016/08/15 20:20:42 Unable to expand dir: exit status 1
2016/08/15 20:20:52 http2: server: error reading preface from client 127.0.0.1:57379: timeout waiting for client preface
2016/08/15 20:20:52 Unable to expand dir: exit status 1
2016/08/15 20:21:02 Unable to expand dir: exit status 1
2016/08/15 20:21:12 Unable to expand dir: exit status 1
2016/08/15 20:21:22 Unable to expand dir: exit status 1
2016/08/15 20:21:32 Unable to expand dir: exit status 1
```

**Comment by evanphx** [comment]
Are more of those lines showing up? If not, it's just from the old run of puma-dev.

**Comment by arrowcircle** [comment]
@evanphx Its new ones

**Comment by evanphx** [comment]
@arrowcircle So it's working though?

**Comment by evanphx** [comment]
@arrowcircle can you type `which getent` into your shell and tell me if it says you have one? I'm trying to track down why the home directory calculation seems to fail for you randomly.

**Comment by arrowcircle** [comment]
@evanphx Apps are working, but first run is always 'unexpected exit'. After reloading page it works ok.

here is the output of `which getent`

```
getent () {
	if [[ $2 = <-> ]]
	then
		grep ":$2:[^:]*$" /etc/$1
	else
		grep "^$2:" /etc/$1
	fi
}
```
If needed, I can share teamviewer session.
Thanks for the great project!
