### ISSUE TITLE
puma-dev does not load the appropriate gemset

### ISSUE THREAD

**Issue by jjmonsalveg** [puma/puma-dev#89]
Hi, I have tried to install and use puma-dev on ubuntu 16.04, i'm using rvm and gemset established by a .rmvrc file in the root of the project, but fails load of gemset . I'm following this steps :
1.  follow the manual to install [dev-tld-resolver](https://github.com/puma/dev-tld-resolver)
2.   test dev-tld-resolver

> ```
> ping -c3 test.dev
> ```

```
PING test.dev (127.0.0.1) 56 (84) bytes of data.
64 bytes from localhost (127.0.0.1): icmp_seq = 1 ttl = 64 time = 0.045 ms
64 bytes from localhost (127.0.0.1): icmp_seq = 2 ttl = 64 time = 0.065 ms
64 bytes from localhost (127.0.0.1): icmp_seq = 3 ttl = 64 time = 0.066 ms

Test.dev --- ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 1999ms
rtt min / avg / max / MDEV = 0,045 / 0,058 / 0,066 / 0,013 ms

```

3.download puma-dev-v0.10-linux-amd64.tar.gz and extract it

4.when running puma-dev, add link to app(ln -s) and accessed from the browser iview.dev

> ./puma-dev

```
* Directory for apps: /home/jj/.puma-dev
* Domains: dev
* HTTP Server port: 9280
* HTTPS Server port: 9283
! Puma dev listening on http and https
! Booting app 'iview' on socket /home/jj/.puma-dev/iview/tmp/puma-dev-23803.sock
iview[23959]: bundler: failed to load command: puma (/home/jj/.rvm/gems/ruby-2.3.1/bin/puma)
iview[23959]: Bundler::GitError: git://github.com/mnoack/nulldb.git (at aa36e3c@aa36e3c) is not yet checked out. Run `bundle install` first.
iview[23959]:   /home/jj/.rvm/gems/ruby-2.3.1/gems/bundler-1.12.5/lib/bundler/source/git.rb:192:in `rescue in load_spec_files'
iview[23959]:   /home/jj/.rvm/gems/ruby-2.3.1/gems/bundler-1.12.5/lib/bundler/source/git.rb:189:in `load_spec_files'
iview[23959]:   /home/jj/.rvm/gems/ruby-2.3.1/gems/bundler-1.12.5/lib/bundler/source/path.rb:95:in `local_specs'
iview[23959]:   /home/jj/.rvm/gems/ruby-2.3.1/gems/bundler-1.12.5/lib/bundler/source/git.rb:160:in `specs'
iview[23959]:   /home/jj/.rvm/gems/ruby-2.3.1/gems/bundler-1.12.5/lib/bundler/lazy_specification.rb:56:in `__materialize__'
iview[23959]:   /home/jj/.rvm/gems/ruby-2.3.1/gems/bundler-1.12.5/lib/bundler/spec_set.rb:91:in `block in materialize'
iview[23959]:   /home/jj/.rvm/gems/ruby-2.3.1/gems/bundler-1.12.5/lib/bundler/spec_set.rb:88:in `map!'
iview[23959]:   /home/jj/.rvm/gems/ruby-2.3.1/gems/bundler-1.12.5/lib/bundler/spec_set.rb:88:in `materialize'
iview[23959]:   /home/jj/.rvm/gems/ruby-2.3.1/gems/bundler-1.12.5/lib/bundler/definition.rb:140:in `specs'
iview[23959]:   /home/jj/.rvm/gems/ruby-2.3.1/gems/bundler-1.12.5/lib/bundler/definition.rb:185:in `specs_for'
iview[23959]:   /home/jj/.rvm/gems/ruby-2.3.1/gems/bundler-1.12.5/lib/bundler/definition.rb:174:in `requested_specs'
iview[23959]:   /home/jj/.rvm/gems/ruby-2.3.1/gems/bundler-1.12.5/lib/bundler/environment.rb:19:in `requested_specs'
iview[23959]:   /home/jj/.rvm/gems/ruby-2.3.1/gems/bundler-1.12.5/lib/bundler/runtime.rb:14:in `setup'
iview[23959]:   /home/jj/.rvm/gems/ruby-2.3.1/gems/bundler-1.12.5/lib/bundler.rb:95:in `setup'
iview[23959]:   /home/jj/.rvm/gems/ruby-2.3.1/gems/bundler-1.12.5/lib/bundler/setup.rb:19:in `<top (required)>'
iview[23959]:   /home/jj/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
iview[23959]:   /home/jj/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
! Killing 'iview' (23959)
* App 'iview' shutdown and cleaned up
! Detecting app 'iview' dying on start

```

How I can do it correctly?, thanks

**Comment by etherdev** [comment]
The only thing I could get to work was setting the ruby version as rvm default and then running bundle on the global gemset for that version. Not great.
